--CREATE DATABASE FoodOrdering;

USE FoodOrdering;


CREATE TABLE Restaurant (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(100) NOT NULL,
    Image VARCHAR(200) NOT NULL,
    Description VARCHAR(MAX)
);

CREATE TABLE Menu (
    Id INT PRIMARY KEY IDENTITY(1,1),
    RestaurantId INT NOT NULL FOREIGN KEY REFERENCES Restaurant(Id),
    Name VARCHAR(100) NOT NULL
);

CREATE TABLE MenuItem (
    Id INT PRIMARY KEY IDENTITY(1,1),
    MenuId INT NOT NULL FOREIGN KEY REFERENCES Menu(Id),
    Name VARCHAR(100) NOT NULL,
    Price DECIMAL(10,2) NOT NULL,
    Image VARCHAR(200) NOT NULL,
    Description VARCHAR(MAX),
    Category VARCHAR(50)
);


CREATE TABLE [User] (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Phone VARCHAR(20) NOT NULL,
    Password VARCHAR(200) NOT NULL
);

CREATE TABLE Orders (
    Id INT PRIMARY KEY IDENTITY(1,1),
    UserId INT NOT NULL FOREIGN KEY REFERENCES [User](Id),
    RestaurantId INT NOT NULL FOREIGN KEY REFERENCES Restaurant(Id),
    TotalPrice DECIMAL(10,2),
    Status VARCHAR(50) DEFAULT 'PENDING',
    CreatedAt DATETIME DEFAULT GETDATE()
);
 
 CREATE TABLE OrderItem (
    Id INT PRIMARY KEY IDENTITY(1,1),
    OrderId INT NOT NULL FOREIGN KEY REFERENCES Orders(Id),
    MenuItemId INT NOT NULL FOREIGN KEY REFERENCES MenuItem(Id),
    Quantity INT NOT NULL,
    Price DECIMAL(10,2) NOT NULL
);

